sonar.projectKey=B-Harish-Azka-Firdaus-2406435805_Modul-1-Coding-Standards
sonar.organization=b-harish-azka-firdaus-2406435805
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes